name: CI

on: [push, pull_request]

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy, rustfmt

      - run: cargo clippy
      - run: cargo fmt --check
